import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CTA, Container, Eyebrow, PageHero, SectionHeading } from "@/components/marketing/layout";

export const Route=createFileRoute("/trademall-ads")({head:()=>({meta:[{title:"TradeMall Ads, Targeted Advertising by Mackdish"},{name:"description",content:"Advertise through TradeMall, the Mackdish-owned digital advertising network, with location, device and schedule targeting."},{property:"og:title",content:"TradeMall Ads, Targeted Advertising by Mackdish"},{property:"og:description",content:"Advertise through TradeMall, the Mackdish-owned digital advertising network, with location, device and schedule targeting."},{property:"og:type",content:"website"},{property:"og:url",content:"https://mackdish.store/trademall-ads"}],links:[{rel:"canonical",href:"https://mackdish.store/trademall-ads"}]}),component:Page});

const placements=["728×90 banner","300×250 display","320×50 mobile","Responsive placements"];
const targeting=["Country","County","City","Device","Browser / OS","Category","Schedule"];

function Page(){return <>
<PageHero eyebrow="TradeMall / a Mackdish product" title="Another route to the customer, beyond social and search." description="TradeMall is Mackdish's advertising network. We use it when a campaign needs additional digital distribution, with the click routed to your website, landing page or WhatsApp."/>
<section className="py-20 sm:py-28"><Container><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><Eyebrow>How the campaign works</Eyebrow><h2 className="mt-4 font-display text-4xl font-semibold">The advert is only the first step.</h2><p className="mt-5 leading-8 text-muted-foreground">We plan the audience, placement and destination together so the person who clicks knows what to do next.</p><Button asChild size="lg" className="mt-8"><Link to="/contact">Plan a TradeMall campaign <ArrowRight/></Link></Button></div><div className="border bg-background"><div className="grid sm:grid-cols-3">{["Advertiser","TradeMall placement","Customer action"].map((x,i)=><div key={x} className="border-b p-6 sm:border-b-0 sm:border-r last:border-r-0"><p className="text-xs font-bold uppercase text-primary">0{i+1}</p><h3 className="mt-12 font-display text-xl font-semibold">{x}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{i===0?"Offer, creative and campaign setup.":i===1?"Targeted digital inventory across the network.":"Website, landing page or WhatsApp conversation."}</p></div>)}</div></div></div></Container></section>
<section className="border-y bg-ink py-20 text-ink-foreground sm:py-28"><Container><div className="grid gap-12 lg:grid-cols-2"><div><Eyebrow>Ad formats</Eyebrow><h2 className="mt-4 font-display text-4xl font-semibold">Formats built for desktop and mobile.</h2><div className="mt-8 grid grid-cols-2 gap-px bg-ink-border">{placements.map(x=><div key={x} className="bg-hero-step p-6 font-semibold">{x}</div>)}</div></div><div><Eyebrow>Targeting</Eyebrow><h2 className="mt-4 font-display text-4xl font-semibold">Choose who sees the campaign.</h2><div className="mt-8 flex flex-wrap gap-2">{targeting.map(x=><span key={x} className="border border-ink-border px-3 py-2 text-sm">{x}</span>)}</div><p className="mt-7 text-sm leading-7 text-ink-muted">Targeting availability depends on the campaign and inventory. We confirm the usable options during setup.</p></div></div></Container></section>
<section className="py-20 sm:py-28"><Container><SectionHeading eyebrow="Where TradeMall fits" title="Use it as one channel inside a broader campaign." description="TradeMall can sit alongside Meta, Google, SEO, a landing page and WhatsApp follow-up. The right mix depends on the offer and audience."/><div className="mt-10 grid gap-4 border-t sm:grid-cols-3">{["Product promotion","Local business enquiries","Website traffic"].map(x=><div key={x} className="border-b py-6"><h3 className="font-display text-xl font-semibold">{x}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Start with a clear offer and a destination that makes the next action easy.</p></div>)}</div></Container></section>
<CTA title="Have an offer you want more people to see?" description="Tell us the audience, location and action you want. We’ll map the TradeMall campaign around it." primary="Advertise on TradeMall" to="/contact"/>
</>}