import { Link } from "@tanstack/react-router";
import { ArrowRight, Check, type LucideIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export function Container({ children, className }: { children: React.ReactNode; className?: string }) { return <div className={cn("mx-auto w-full max-w-7xl px-5 lg:px-8", className)}>{children}</div>; }
export function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="mb-4 text-xs font-bold uppercase text-primary">{children}</p>; }
export function SectionHeading({ eyebrow, title, description, align = "left" }: { eyebrow?: string; title: string; description?: string; align?: "left" | "center" }) { return <div className={cn("max-w-3xl", align === "center" && "mx-auto text-center")}>{eyebrow && <Eyebrow>{eyebrow}</Eyebrow>}<h2 className="font-display text-3xl font-semibold leading-tight text-foreground sm:text-4xl lg:text-5xl">{title}</h2>{description && <p className="mt-5 text-base leading-8 text-muted-foreground sm:text-lg">{description}</p>}</div>; }
export function PageHero({ eyebrow, title, description, icon: Icon }: { eyebrow: string; title: string; description: string; icon?: LucideIcon | undefined }) { return <section className="relative overflow-hidden border-b bg-hero py-20 sm:py-28"><Container><div className="max-w-4xl">{Icon && <div className="mb-8 grid size-12 place-items-center rounded-md border border-primary/30 bg-primary/10 text-primary"><Icon /></div>}<Eyebrow>{eyebrow}</Eyebrow><h1 className="font-display text-4xl font-semibold leading-[1.06] text-hero-foreground sm:text-6xl lg:text-7xl">{title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-hero-muted sm:text-xl">{description}</p></div></Container></section>; }
export function CTA({ title = "Ready to turn your digital presence into a growth system?", description = "Start with a practical review of your current channels, gaps and opportunities.", primary = "Get a Free Digital Audit", to = "/digital-audit", secondary = "Book a Consultation" }: { title?: string; description?: string; primary?: string; to?: string; secondary?: string }) { return <section className="bg-primary py-16 text-primary-foreground sm:py-20"><Container className="flex flex-col items-start justify-between gap-8 lg:flex-row lg:items-center"><div className="max-w-3xl"><h2 className="font-display text-3xl font-semibold sm:text-4xl">{title}</h2><p className="mt-4 max-w-2xl text-primary-foreground/75">{description}</p></div><div className="flex flex-wrap gap-3"><Button asChild size="lg" variant="secondary"><Link to={to}>{primary}<ArrowRight /></Link></Button>{secondary && <Button asChild size="lg" variant="outline" className="border-primary-foreground/30 bg-transparent text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground"><Link to="/contact">{secondary}</Link></Button>}</div></Container></section>; }
export function FeatureList({ items, columns = 2 }: { items: string[]; columns?: 2 | 3 }) { return <ul className={cn("grid gap-3", columns === 2 ? "sm:grid-cols-2" : "sm:grid-cols-2 lg:grid-cols-3")}>{items.map((item) => <li key={item} className="flex items-start gap-3 text-sm leading-6 text-foreground"><span className="mt-0.5 grid size-5 shrink-0 place-items-center rounded-full bg-primary/10 text-primary"><Check className="size-3" /></span>{item}</li>)}</ul>; }
